FROM mcr.microsoft.com/devcontainers/rust:1-1-bullseye

#VOLUME [ "/usr/local/cargo" ]

RUN sudo apt-get update \
  && sudo apt-get install -y g++ pkg-config libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev