name: CI

on:
  push:
    pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y g++ pkg-config libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Fix
        run: cargo fix --all
      - name: Clippy
        run: cargo clippy
      - name: Run Tests
        run: cargo test