name: Deploy

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y g++ pkg-config libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: "bevy-example-release"
          path: "./target/release/bevy-example"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Build Release
        run: cargo build --release
      